// Code generated by goctl. DO NOT EDIT!
// Source: userService.proto

package server

import (
	"context"

	"zeroService/rpc/internal/logic"
	"zeroService/rpc/internal/svc"
	"zeroService/rpc/userService"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

// 注册
func (s *UserServiceServer) Register(ctx context.Context, in *userService.RegisterRequest) (*userService.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}
