// Code generated by goctl. DO NOT EDIT.
package types

type HttpResponse struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type RegisterReq struct {
	UserName string `form:"username"`
	Pwd      string `form:"pwd"`
	NickName string `form:"nickname"`
	Age      int    `form:"age"`
}

type RegisterRsp struct {
	Rid int `json:"rid"`
}

type InfoReq struct {
	Rid int `form:"rid"`
}

type InfoRsp struct {
	Rid      int    `json:"rid"`
	UserName string `json:"username"`
	Pwd      string `json:"pwd"`
	NickName string `json:"nickname"`
	Age      int    `json:"age"`
}
